### ISSUE TITLE
Global Search not working

### ISSUE THREAD

**Issue by benji1304** [dannysummerlin/force-navigator#20]
When using the '?' command to trigger a global search and hitting return, then nothing happens.

The Chrome console shows this
```javascript
main.js:85 Uncaught Error: Extension context invalidated.
    at goToUrl (main.js:85:55)
    at invokeCommand (main.js:81:5)
    at kbdCommand (main.js:378:4)
    at E (mousetrap.min.js:22:1095)
    at Object.S [as handleKey] (mousetrap.min.js:22:1480)
    at HTMLInputElement.x (mousetrap.min.js:22:1723)
goToUrl @ main.js:85
invokeCommand @ main.js:81
kbdCommand @ main.js:378
E @ mousetrap.min.js:22
S @ mousetrap.min.js:22
x @ mousetrap.min.js:22
```

**Comment by benji1304** [comment]
Cannot replicate anymore - whilst I was in Setup > Territory Model > Hierarchy > Manage Users then the lightning navigator wouldn't do anything. I navigated home, and now it's working fine again!
